blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/saiakhil-devops/github-actions-devops-pipeline/security/policy
    about: Please report security issues via the Security Policy.
