name: trivy
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }
  schedule:
    - cron: "0 4 * * 1"   # Mondays 04:00 UTC

jobs:
  trivy-fs:
    name: Trivy FS scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trivy FS (table + SARIF)
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "HIGH,CRITICAL"
          exit-code: "1"         # fail build on HIGH/CRITICAL

      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
